version: '3.9'

services:
  web:
    build:
      context: .
    command: >
      sh -c "./wait-for-it.sh db:5432 -- 
             ./wait-for-it.sh redis:6379 -- 
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=cinema.settings_prod
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydatabase
      - DB_HOST=db
      - DB_PORT=5432

  celery:
    build:
      context: .
    command: celery -A cinema worker --loglevel=info
    depends_on:
      - redis
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=cinema.settings_prod
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

  beat:
    build:
      context: .
    command: celery -A cinema beat --loglevel=info
    depends_on:
      - redis
      - db

    environment:
      - DJANGO_SETTINGS_MODULE=cinema.settings_prod
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      retries: 5

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "myuser", "-d", "mydatabase" ]
      interval: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local
