# Generated by Django 5.1.2 on 2024-10-13 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_app', '0003_genre_remove_movie_genre_movie_genres'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='genres',
            new_name='genre',
        ),
    ]
