# Generated by Django 5.1.2 on 2024-10-18 20:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_app', '0007_ticket_seat_number_alter_hall_capacity_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='hall',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Зал'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['release_date'], name='cinema_app__release_0da1a6_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['session_date', 'start_time'], name='cinema_app__session_c8c514_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['hall'], name='cinema_app__hall_id_ad6540_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['movie'], name='cinema_app__movie_i_e814fe_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['session', 'seat_number'], name='cinema_app__session_fb52b2_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['users'], name='cinema_app__user_id_1bd039_idx'),
        ),
    ]
