# Generated by Django 5.1.2 on 2024-10-19 00:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_app', '0008_alter_hall_name_movie_cinema_app__release_0da1a6_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='base_ticket_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Ціна'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='session',
            name='hall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema_app.hall', verbose_name='Зал'),
        ),
        migrations.AlterField(
            model_name='session',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema_app.movie', verbose_name='Фільм'),
        ),
    ]
