# Generated by Django 5.1.2 on 2024-10-20 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_app', '0009_session_ticket_price_alter_session_hall_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='seat_number',
            field=models.PositiveIntegerField(db_index=True, verbose_name='Номер місця'),
        ),
    ]
