# Generated by Django 5.1.2 on 2024-10-24 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_app', '0011_alter_session_end_time_alter_ticket_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='sold_tickets',
        ),
    ]
