# Generated by Django 5.1.2 on 2024-10-25 06:24

import cinema_app.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_app', '0012_remove_session_sold_tickets'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='original_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Оригінальна назва'),
        ),
        migrations.AddField(
            model_name='movie',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to=cinema_app.utils.poster_upload_to),
        ),
    ]
