# Generated by Django 5.1.2 on 2024-11-02 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_app', '0016_remove_ticket_cinema_app__user_id_1bd039_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='original_name',
            field=models.CharField(max_length=100, verbose_name='Оригінальна назва'),
        ),
    ]
