# Generated by Django 5.1.2 on 2024-11-28 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_app', '0018_order_ticket_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('Reserved', 'Reserved'), ('Booked', 'Booked')], default='Reserved', max_length=20),
        ),
    ]
