# Generated by Django 5.1.2 on 2024-11-28 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_app', '0019_ticket_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('reserved', 'Reserved'), ('booked', 'Booked'), ('cancelled', 'Cancelled')], default='reserved', max_length=20),
        ),
    ]
