# Generated by Django 5.1.2 on 2024-12-03 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_app', '0022_order_stripe_session_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='stripe_session_id',
        ),
    ]
